### ISSUE TITLE
developing the java component

### ISSUE THREAD

**Issue by bryantChhun** [micro-manager/pycro-manager#123]
Simple question that might be useful for others:

Because pycro-manager and micro-manager are separate repositories, how does one develop and test pycro-manager on the java side?

The Java component appears to have modules (remote and internal.zmq) that are added to the [Studio](https://github.com/micro-manager/micro-manager/tree/master/mmstudio/src/main/java/org/micromanager).  So I assume that running micro-manager from IDE (IntelliJ) in debug mode needs to include files from both repos during compilation of the Studio.

I can add both sources to the project, but run into the following error:
```
java.io.FileNotFoundException: /Applications/Micro-Manager-2.0.0-gamma1-20200914/plugins (Is a directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at org.micromanager.internal.zmq.ZMQUtil.getPackagesFromJars(ZMQUtil.java:399)
	at org.micromanager.internal.zmq.ZMQServer.<init>(ZMQServer.java:75)
	at org.micromanager.internal.MMStudio.runZMQServer(MMStudio.java:941)

```

**Comment by henrypinkard** [comment]
The Studio depends on PycroManagerJava.jar, which includes both `remote ` and `internal.zmq` packages. The only explicit call to either package is [here](https://github.com/micro-manager/micro-manager/blob/524e6f55a392082fcb47fc12820f90a935776246/mmstudio/src/main/java/org/micromanager/internal/MMStudio.java#L914) to instantiate a ZMQ server. All other objects from these packages are generated by interacting with this server (or subsequent servers that it spawns).

So if you want to develop the Java side, that's correct, you need to include the source of these packages. In addition many of the features used by Pycromanager live in seperate repositories. Specifically [NDViewer, the image display window](https://github.com/micro-manager/NDViewer), [NDTiffStorage, the disk storage](https://github.com/micro-manager/NDTiffStorage), and [AcqEngJ, the acquisition engine](https://github.com/micro-manager/AcqEngJ). PycroManagerJava depends on all of these. So depending on what you're trying to do you might want to add the source for these as well.

Here is how I set everything up in IntelliJ. Under **File-project structure** I have a module for each one. Also shown are Magellan, which is not necessary and micromanager, which contains the studio source code and is also not necessary (i.e. you could just use MMJ_.jar instead). 

<img width="420" alt="Screen Shot 2020-09-18 at 7 35 51 AM" src="https://user-images.githubusercontent.com/7969470/93610373-d5209080-f981-11ea-9580-2df93700a601.png">

Sources and dependencies are set up for pycromanager as shown:

<img width="1295" alt="Screen Shot 2020-09-18 at 7 39 45 AM" src="https://user-images.githubusercontent.com/7969470/93611152-c9819980-f982-11ea-8610-f5f077497e10.png">

<img width="1292" alt="Screen Shot 2020-09-18 at 7 43 34 AM" src="https://user-images.githubusercontent.com/7969470/93611120-be2e6e00-f982-11ea-9859-74184236486b.png">


mmLibraries contains all the Jars within the `plugins/Micro-Manager` folder of a micro-manager install, except for the ones that you're running from source (i.e. NDViewer, AcqEngJ, NDTiffStorage, and MMJ_, which is the compiled version of studio source code though its [name may change in the future](https://github.com/micro-manager/micro-manager/issues/922)). MMCoreJ is separated out here even though it's also in this folder so that it can be separately used as a dependency for the other three libraries without having to include everything else in that folder.

NDTiffStorage and AcqEngJ are set up similarly. Their only dependency is MMCoreJ. NDViewer has an extra dependency, and has a resources folder as shown:

<img width="1292" alt="Screen Shot 2020-09-18 at 7 53 18 AM" src="https://user-images.githubusercontent.com/7969470/93612225-1d40b280-f984-11ea-9c70-b68400ddfcf6.png">

<img width="1292" alt="Screen Shot 2020-09-18 at 7 50 41 AM" src="https://user-images.githubusercontent.com/7969470/93612231-1e71df80-f984-11ea-8241-24efc4810714.png">


Lastly, you need to setup a run configuration. Here the **working directory** is the root of your micro-manager install:

<img width="1072" alt="Screen Shot 2020-09-18 at 7 54 59 AM" src="https://user-images.githubusercontent.com/7969470/93612403-4feaab00-f984-11ea-993c-78f15ea221ba.png">

**Comment by bryantChhun** [comment]
I got everything set up as above, but launching the pycromanager or micromanager configuration does not run micro-manager (but does open ImageJ).  I've done the "command-drag-to-desktop" trick to get around OSX security, but MM still won't launch.

**Comment by henrypinkard** [comment]
I would guess this a problem with either your working directory in the run configuration or the MMJ_.jar library or micro-manager studio source as added to the project. 

Do you see **Micro-Manager** in the IamgeJ plugins menu?

**Comment by bryantChhun** [comment]
Indeed I can see micro-manager in the ImageJ plugin menu.  But when I select the Studio it gives me this error (in IntelliJ console)
![image](https://user-images.githubusercontent.com/25647712/93817270-8d159e00-fc0d-11ea-8f68-e4e55057d9df.png)

I added the MMJ_.jar from my nightly build installation to the mmLibraries -- then everything worked perfectly.  So clearly the problem is somewhere during my compilation of studio from source.

**Comment by bryantChhun** [comment]
Ok I solved it.  My micro-manager config did not include resources as a content root.  Including resources fixed it.

Thanks for all the help!  Looking forward to contributing.

**Comment by henrypinkard** [comment]
Great!
