### ISSUE TITLE
Why not use Py4J

### ISSUE THREAD

**Issue by nanthony21** [micro-manager/pycro-manager#14]
As far as I can tell py4j does the same thing as pycromanager when it comes to general-purpose Java/Python interfacing via sockets. Py4J is fairly mature, well-documented, and is used in other major projects. It also implements handling for things which I don't believe are in pycromanager such as exception handling, multithreading etc.

If pycromanager relied on py4j rather than implementing all the low-level language interfacing from scratch via zmq then that would free up much more development time for functionality that is specific to Micro-Manager.

**Comment by henrypinkard** [comment]
I tried Py4j first. It was painfully slow when moving large byte arrays. Hence the development of the ZeroMQ framework that is now pycromanager core. 

There actually is exception handling and multithreading in the pycromanager core. Exceptions propagate from Java to python. Multithreading is achieved using `new_socket=True` when making Java objects. There are also additional features not supported by py4j (like zmq push pull sockets)

Probably long term it makes sense long term to split out the core module to its own separate library that is essentially a faster version of py4j, since the low level interfacing is unrelated to micro-manager

**Comment by nanthony21** [comment]
Thanks @henrypinkard ,

That makes sense. I looked, and I guess even the lead developer of Py4j recommends transferring large arrays separately through shared memory or a separate socket so it looks like pycromanager is doing the right thing in that respect.

Do you know if there is a way to to register python code as a listener for an event in Java like described here?: https://www.py4j.org/advanced_topics.html#implementing-java-interfaces-from-python-callback

I can see this being a pretty useful capability for Micro-Manager.

**Comment by henrypinkard** [comment]
I don't think this is possible without some tricks to coordinate Python and Java sides (which they appear to have done there). An event listener basically boils down to the problem of knowing when a method is invoked on a specific instance of an object on the Java side (which could then be automatically propagated to the Python shadow of that object). I don't know of any way of "listening" for this on a generic object in Java. So there would have to be some coordination from the python side to make this apply to specific classes (which could then implement listener interfaces, as they've done in py4j). But this would require a different socket setup than is currently implemented (Python server, Java client instead of the other way around). Given the complexity this would add, and the fact that it would require a specialized object on Java side anyway, I think it would make more sense to just create a Java object that listens to whatever events and collects them. Then a python shadow of that object (with it's own dedicated socket) could  be created and constantly polled for new events. I don't think this would add a ton of overhead, since projects like Jupyter are continuously polling over zmq.
