### ISSUE TITLE
possible to save with other tiff formats

### ISSUE THREAD

**Issue by ianhi** [micro-manager/pycro-manager#142]
Is it possible to specify the data format (e.g. `ome.tiff`)? This would make it much easier to use with existing code/workflows as well as enable easier sharing of data with collaborators who want to use Fiji to explore the data.

**Comment by ianhi** [comment]
It seems like the answer is currently no, but I thought I'd ask regardless. If indeed the answer is no is there a clear path I could follow to add that functionality to the library?

**Comment by henrypinkard** [comment]
In a general sense probably not since the OME data model is a lot more rigid than the types of acquisitions pycromanager allows. you could either

1) divert images away from default saving using an image processor and then make a python ome tiff writer. This would be slowish since you have to pass data through java python bridge. Also you'd either lose data or double save data if you want to use default viewer during acq.

2) Dig into the Java code and try to figure out how you can make the OME metadata get written at the end of acquisition, inferring things like missing axes and the like

**Comment by henrypinkard** [comment]
Thinking about this some more, option 2 would actually be an awesome contribution. You could automatically convert to OME tiff at dataset close time if the collected data were consistent with the OME Tiff specification. Wouldnt be so difficult because [NDTiffStorage](https://github.com/micro-manager/NDTiffStorage) was derived from the mircomanager stack that used to save OME tiffs, so you'd just have to restore that functionality. It'd be a pure Java project. I could guide you through it.

**Comment by ianhi** [comment]
Rad. I think I would definitely need some guidance around μmanager code but I agree that this would be great to have. Though now that I'm less caught in the moment I don't think I'll have time for pursuing this in the immediate future unfortunately :(.

As a related suggestion have you thought much about [xarray](http://xarray.pydata.org/en/stable/)? It works with a dask backend and allows for labelled axes so if pycromanager loaded into xarray it would be super cool.

**Comment by henrypinkard** [comment]
Okay, no worries. If you find the time and what to take a stab I'm happy to guide you.

Hadn't heard of xarray, but yeah that looks like it'd be a cool addition too

**Comment by henrypinkard** [comment]
Should add also that auto-conversion to OME-TIFF, if added, should be an option that one must enable, since it will likely lead to delays at the end of collecting big datasets (https://forum.image.sc/t/finishing-files-takes-long-time-to-finish-in-micro-manager/43756/2)

**Comment by henrypinkard** [comment]
Probably more likely that the OME-Tiff saving in Micro-Manager gets split out into its own library, then could be added to pycro-manager. Closing for now
