### ISSUE TITLE
How can one call Python code from the Java side?

### ISSUE THREAD

**Issue by nicost** [micro-manager/pycro-manager#183]
Hopefully not a feature request, but a question;).  Once I have a working pycromanager bridge establised, is it possible for the Java code to call a function on the Python side and get the result returned?  I guess the technique will be similar to the image-process_fn in pycromanager.Acquisition (which establishes a callback function provided by the Python side). So, the question is probably more: How do I create a Java function that can take a Python method as an argument?  Do I need to make changes in the Pycro-Manager layer to do so , or can I do this completely on the Java side?

**Comment by henrypinkard** [comment]
Theres not really a generic mechanism for this right now. image_process_fn is continuously waiting for Images to be pushed form the java side and then sending them back. See here:

https://github.com/micro-manager/pycro-manager/blob/083e88b7f6df1f8d6864f726d0fa3b99f0437550/pycromanager/acquire.py#L78

This uses dedicated threads on both the java and python side

I think the best most generic way to this (which doesn't exist at the moment), would be to recreate Python-Java version of what exists with Java-Python. But this would require some work: a server on the Python side and client on the Java side, so that Java could create "shadowed" python objects in the same way that Python can currently create "shadowed" Java objects. I think this would be a worthwhile addition, but probably won't have the bandwidth to add any time soon.

Depending on what youre trying to do you could probably create a hacky workaround by making a Java object that accumulates all calls intended for python side then doing `Bridge.construct_java_object('classpath', new_socket=True)` to create an instance of it, then just continuously polling from the python side (maybe in a dedicated thread) to bring any calls over the Bridge

**Comment by nicost** [comment]
I think that for now just having this callback mechanism is great, but it would be nice if it would be easier to create other instances. Do I understand correctly that the Java side first opens another ZMQ bridge? Can you point me to where that happens?

Is it possible to make both the Java and Python code for this more generic, to facilitate creation of such callbacks?  In this specific case, I am thinking about adding the option to use Python for image processing in our "Auto-Photoconverter" plugin (https://www.biorxiv.org/content/10.1101/2020.06.30.179648v1), but can imagine that I and others will run into the same issue more often.  I don't think that a full blown Java-Python bridge is needed, but easing the path to create callbacks would be great.

**Comment by henrypinkard** [comment]
> I think that for now just having this callback mechanism is great, but it would be nice if it would be easier to create other instances. Do I understand correctly that the Java side first opens another ZMQ bridge? Can you point me to where that happens?

I'm not sure at what behavior youre talking about specifically, so let me explain a bit more. When you create a `Bridge` on the python side, under the hood it is a ZMQ-Client in python and a ZMQ-Server in java. These two communicate over a specific port (defaults to 4827). Any Java object that is passed over the bridge to the python side is associated with that port by default, which means that if you ever call a blocking method, nothing else will be able to communicate over that port. Because of this, you can create new Java objects with `Bridge.construct_java_object('classpath', new_socket=True)`. This will create a new `org.micromanager.internal.zmq.ZMQServer` object that has its own thread on the java side listening for client requests. 

If you wanted to have something on the python side constantly polling a java object, you'd most likely want it on its own thread (on both java and pythons sides) and communicating on its own port, otherwise it would mess up any traffic on the main port opened by the bridge. So one option is just making the java object to accumulate messages and a python object to poll for them on a dedicated thread.

If you want to make a more generic mechanisms for this, I'm not sure this is even so much easier than the way this type of behavior _should_ be set up, which is, as i mentioned before, making a mirror of the current behavior so that Java can shadow python objects in addition to python shadowing java objects. The way I picture it, when you first create a `Bridge` from python, it would create a Java client python server in addition to the Java server python client that is already made. Might taking some thinking as to what the differences would be going from a statically compiled language to a dynamic one versus the opposite, but it's definitely possible in some capacity. At the very least, the serialization protocol for passing objects back and forth is already established and can be reused as is

**Comment by henrypinkard** [comment]
Let me know which parts of the code you want me to point you to in this process

**Comment by nicost** [comment]
Can you point me to the code (I think that it is on the Java side, but not sure), where this happens:

> Because of this, you can create new Java objects with Bridge.construct_java_object('classpath', new_socket=True). This will create a new org.micromanager.internal.zmq.ZMQServer object that has its own thread on the java side listening for client requests.

The other part that I do not understand is what the Java code looks like when:

>  image_process_fn is continuously waiting for Images to be pushed form the java side and then sending them back.

How does the Java side "push an image"?  What does it call to send images over the ZeroMQ bridge?  It would be great if you can point me to the Java code that does this.  For now, just being able to replicate what you build to do this would be a big step forward for me;)

**Comment by henrypinkard** [comment]
> Can you point me to the code (I think that it is on the Java side, but not sure), where this happens:
> 
> > Because of this, you can create new Java objects with Bridge.construct_java_object('classpath', new_socket=True). This will create a new org.micromanager.internal.zmq.ZMQServer object that has its own thread on the java side listening for client requests.

Here is where it gets created:

https://github.com/micro-manager/pycro-manager/blob/083e88b7f6df1f8d6864f726d0fa3b99f0437550/java/src/main/java/org/micromanager/internal/zmq/ZMQServer.java#L385

The function in which that runs, `protected byte[] parseAndExecuteCommand(String message)`, is the master function that all commands get routed through. Every instance of `ZMQServer` is just running it continuously and returning a reply each time.

> The other part that I do not understand is what the Java code looks like when:
> 
> > image_process_fn is continuously waiting for Images to be pushed form the java side and then sending them back.
> 
> How does the Java side "push an image"? What does it call to send images over the ZeroMQ bridge? It would be great if you can point me to the Java code that does this. For now, just being able to replicate what you build to do this would be a big step forward for me;)

This is a little confusing because it works with a slightly different mechanism than the other stuff. It's using a different class, a [ZMQPushSocket](https://github.com/micro-manager/pycro-manager/blob/master/java/src/main/java/org/micromanager/internal/zmq/ZMQPushSocket.java). It is essentially doing [this](https://learning-0mq-with-pyzmq.readthedocs.io/en/latest/pyzmq/patterns/pushpull.html), only with one consumer. The "result collector" is [ZMQPullSocket](https://github.com/micro-manager/pycro-manager/blob/master/java/src/main/java/org/micromanager/internal/zmq/ZMQPullSocket.java). These are different sockets that operate on different ports than the ZMQServer, but the share they same code that serializes/deserializes objects/primitives.

These push and pull sockets are managed by a [RemoteImageProcessor](https://github.com/micro-manager/pycro-manager/blob/master/java/src/main/java/org/micromanager/remote/RemoteImageProcessor.java), which is created and destroyed with each acquisition and provides dedicated threads for continuously pushing and continuously pulling


It might make sense to have a ZMQClient java class as well (and a server in python), which wouldn't be too hard since it could inherit the serialization that the other sockets do as well. I think this was part of my original plan, though I never actually got around to implementing it.
