### ISSUE TITLE
Make sure acquisition objects properly clean up

### ISSUE THREAD

**Issue by henrypinkard** [micro-manager/pycro-manager#218]
Right now, after running an acquisition and closing the Python process, you cannot delete the saved data without closing and reponening MM

**Comment by dpshepherd** [comment]
In the recent refactor, did any clues pop up about this? It would be useful for us to be able to move data to a NAS without restarting MM.

**Comment by henrypinkard** [comment]
seems to work now if if you set `acq=None` after the acquisition

**Comment by dpshepherd** [comment]
Did you verify this works on Windows 10? We cannot move or delete files until we close the Micromanager session used to acquire the data on Windows 10 with v0.12.8 and MM 2.0 nightly build 20210407.

We are setting `acq=None` after the `with...` block.

Unfortunately we have to use Windows due to some drivers that aren't available on Linux.

**Comment by henrypinkard** [comment]
You're right, there was some incorrect logic on the Java side. I guess Mac OS is just more permissive about letting you delete stuff thats open in another process. I don't have a windows setup at the moment, but I fixed what I think was the source of it.

In [PycromanagerJava](https://dl.bintray.com/micro-manager/micro-manager/org/micro-manager/pycro-manager/PycroManagerJava/0.21.1/) and [NDViewer](https://dl.bintray.com/micro-manager/micro-manager/org/micro-manager/ndviewer/NDViewer/0.5.1/)
