### ISSUE TITLE
Freeze of ZMQ Dependency to enable compatibility with older version of MM

### ISSUE THREAD

**Issue by camFoltz** [micro-manager/pycro-manager#260]
### Problem

In our lab, we settle on a version of MicroManager that suits our needs, and try not to make any updates for ~6months.  This allows us to settle on a version that is less buggy for our needs, or one where we understand small bugs, and enables development of acquisition code, calibration, etc.  Along with this settlement of MicroManager, we also settle on the version of pycromanager accompanied with that specific build.  However, there are often bug fixes and feature additions to pycromanager that we would like to use with our older build of MicroManager but it seems as though the ZMQ mismatch between latest pycromanager build and older MM build makes this difficult.  I wanted to start the conversation on the implications of a version freeze of ZMQ and how this may impact the interplay with MM (I do not know much on this front).

### Proposed Solution

I am not sure if pycromanager uses a lot of the newest features of ZMQ, so I propose that the version of ZMQ accompanied with pycromanager is frozen, and only updated when absolutely needed.  This would allow us to use newer versions of pycromanager, but still have compatibility with older builds of MM.

I know there is also a java side to this (although I know much less about this side), and I was wondering if this ZMQ freeze on the python side would affect the java components, or if there is a way to replace/re-arrange .jar files such that everything works well with eachother.  @ieivanov may be able to provide insight on this part of the issue.

### Additional context

As biologists start to use this platform widely for acquisition, it will be nice to have stable builds / configurations that work with other tools.  We are developing pipelines in our own repos that use pycromanager / micromanager and it would be great to be able to lay out clear instructions on what versions to use and install.  To do this it would be helpful for us to use newer features of pycromanager, but have pycromanager be compatible with an older stable build of MM that our lab eventually settles on.

Please let me know if I can clarify anything here.

**Comment by ieivanov** [comment]
I'm hoping that if we can alleviate the ZMQ version mismatch between MicroManager and pycromanager, then we can use pycromanager with an order version of MicroManager by pulling the latest version of pycromanager from pypi and placing the most recent compiled .jar files for AcqEngJ, NDViewer, and NDTiffStorage in the MicroManager plugin folder. @henrypinkard let us know if you think this will work.

**Comment by henrypinkard** [comment]
I think there's a straightforward solution to this. I'll explain the architecture and I think this will make sense.

Most of the heavy lifting of Pycro-Manager is actually occurring on the Java side, in the **AcqEngJ** (Acqusition engine), **NDViewer** (Image viewer), and **NDTiffStorage** (Image saving) libraries. These are all independent of one another and depend only on **MMCoreJ**, the Java wrapper to the Micro-Manager core. There's a fourth library, **PycroManagerJava**, which provides a tiny bit of glue code to link all of these together (e.g. an acquisition has a viewer + a data storage instance). In addition, it also contains the Java side of the `Bridge`, which is that transport layer that interconverts Java and Python using ZeroMQ (More about this in the **Architecture and design** section of the supplement of the [PM paper](https://www.nature.com/articles/s41592-021-01087-6#MOESM1)). This probably makes sense to have as its own library independent of Micro-Manager entirely, which may happen in the future.

The ZMQ version mismatch would be better named "transport protocol mismatch", because its not referring to ZMQ itself, but rather how Java objects/functions are serialized into JSON which is then sent over ZMQ sockets. This transport layer only uses a few very basic features of ZMQ which thousands of other projects do as well, so I don't imagine versioning even matters much.

On the Python side, the pip package contains the client side of this zmq transport layer, as well as a layer on top of that that is calling the glue code in **PycroManagerJava**.

These four java libraries live in the Jar files @ieivanov mentions, and they are entirely independent of the rest of Micro-Manager java layer at present. So if you update all 4 of them to their latest versions by manually replacing the jars (available [here](https://dl.bintray.com/micro-manager/micro-manager/org/micro-manager/)) (**Note: this url will change sometime in the future as we find a new hosting platform but it will work just the same**), and you upgrade to the latest pip version of pycromanager, everything should just the same as if you downloaded the latest nightly build.

If **MMCoreJ** changes, this would not be true, you'd have to update everything. But this has yet to happen during the existence of Pycro-Manager, and I don't know why it would any time soon.

One final caveat is that I think @nicost might be messing around with switching the Micro-Manager MDA window to rely on **AcqEngJ**, so in the future you might have to also replace the **MMJ_.jar** file too for everything to work as expected if you're also using that.

**Comment by henrypinkard** [comment]
But really I think the best solution for this is to write unit tests for the stuff that ends up being buggy on your end, so that if and when you upgrade you know exactly whats going wrong without manual testing

**Comment by camFoltz** [comment]
@henrypinkard thanks for the detailed explanation of the architecture -- I am not sure if I had specifically noticed performance issues when the ZMQ server was mismatched, but it is good to know that this shouldn't matter.  It is also great to know that these pycromanager jar files are only dependent on MMCoreJ and can be replaced.

I think the solution that makes sense for us is to replace the Jar files in our earlier MM builds as well as upgrade pycromanager via pip.  Unit tests are also a good idea for the future to track these bugs.

One clarification question on that final caveat:  If @nicost changes around the MDA engine, this won't affect the older build's interaction with pycromanager correct?  Or are you saying that the pycromanager Jars may also be changed in this case, such that we will need to replace the **MMJ_.jar** file as well during this pseudo-upgrade procedure?

Thanks for your help on all of this!

**Comment by henrypinkard** [comment]
> I am not sure if I had specifically noticed performance issues when the ZMQ server was mismatched

If it does lead to a problem, it wouldn't be performance, it would be some function in the API not working at all or working in some unexpected way. But I think this code is pretty much stabilized now, so hopefully you won't run into this at all.

> I think the solution that makes sense for us is to replace the Jar files in our earlier MM builds as well as upgrade pycromanager via pip. Unit tests are also a good idea for the future to track these bugs.

Yeah makes sense to me

> One clarification question on that final caveat: If @nicost changes around the MDA engine, this won't affect the older build's interaction with pycromanager correct? Or are you saying that the pycromanager Jars may also be changed in this case, such that we will need to replace the **MMJ_.jar** file as well during this pseudo-upgrade procedure?

He would be changing the MDA engine to use AcqEngJ. So this might entail fixing stuff in AcqEngJ as well. Pycro-Manager will always be using the latest version of AcqEngJ, so you'd just want to do as you said and replace MMJ_ as well with a version that you build yourself or grab from a newer build.

> Thanks for your help on all of this!

You're welcome!

**Comment by ieivanov** [comment]
Thanks @henrypinkard!

**Comment by ieivanov** [comment]
@henrypinkard the link to the jar files did change, as you said - can you please add the new link here? Is the strategy we discussed in this issue still the best for using older MM versions with the latest pycromanager version?

**Comment by henrypinkard** [comment]
Yes, the previous repo was discontinued, so they're now here: https://s01.oss.sonatype.org/#nexus-search;quick~micro-manager

This is still how it is set up, but in general, I would strongly encourage you to not use this strategy and instead, if you're going to update anything at all, just stay up to date with the latest nightly builds. I wouldn't expect that the hardware layer is changing much anyway, and this manual way of updating pycromanager is less robust and not guaranteed to be future proof

**Comment by ieivanov** [comment]
Thanks Henry!

We have previously experienced problems where sometimes a device adapter would update between different MM builds and our acquisition would not work the same way anymore. For now, our strategy is to stick to a given nightly build that we know works well, and update only if we need to, and after we have done proper testing.  

It would be great to have a periodic (say monthly) MM version log summarizing what features have changed. Is there an easy way to construct that, maybe based on commit history, or files changed?

**Comment by henrypinkard** [comment]
I get that. But I think the same thing could happen if you're updating PM, and you have the additionally possibility of introducing version mismatch bugs that wouldn't otherwise arise. Less work in the long run, I would think, to update everything at once periodically.

> It would be great to have a periodic (say monthly) MM version log summarizing what features have changed. Is there an easy way to construct that, maybe based on commit history, or files changed?

I think its a good idea. Maybe @marktsuchida knows?

**Comment by nicost** [comment]
Run:

`git log --since="last month" --pretty=format:'%h,%an,%ar,%s' > log.csv`

on both micro-manager and mmCoreAndDevices.

> We have previously experienced problems where sometimes a device adapter would update between different MM builds and our acquisition would not work the same way anymore.

Please let the device adapter (or us if unreachable) know.  Sometimes small changes can have unintended and unexpected consequences.  Without feedback, nobody has a change to make things work better.
