### ISSUE TITLE
Dataset.as_array() returns array of wrong size

### ISSUE THREAD

**Issue by ptbrown1729** [micro-manager/pycro-manager#278]
### Bug report

Dataset.as_array() returns arrays of the wrong size.

```
import pycromanager as pm

ds= pm.Dataset(path)
ds.image_height
ds.image_width

arr = ds.as_array()
arr.shape
```

ds.image_height = 252
ds.image_height = 2304

the expectation is that arr.shape = (25, 3000, 252, 2304)
but instead, arr.shape = (25, 3000, 252, 252)

Looks like this is caused by line 549 of data.py, which reads
```
w = self.image_height if not stitched else self._tile_width
```

but should instead read
```
w = self.image_width if not stitched else self._tile_width
```

After making this change, the arr is returned with the correct size

**Version Info**
  * Operating system: Linux Mint 19.3
  * pycromanager version: 0.10.9 
  * Python version: 3.8.5
  * conda environment

**Comment by ptbrown1729** [comment]
Update: in pycromanager 0.12.8 arr is the correct size. It still looks like line 549 has a bug, but I guess this variable w is not used in that case.

**Comment by henrypinkard** [comment]
Thanks for the detailed report. You're right--clearly a typo, but it looks like only matters if you've got missing images in your dataset that are getting filled in with blanks.  

In between those two version I added a bunch of features to the `Dataset` class (still need to put them in documentation), so that would explain the fix
