### ISSUE TITLE
does it work with multiprocessing?

### ISSUE THREAD

**Issue by josepNTU** [micro-manager/pycro-manager#31]
Hi!

I'm very interested in using PycroManager. I'd like to use python's multiprocessing to do data acquisition with micro-manager. Would it work?

KR,

Josep

**Comment by henrypinkard** [comment]
It should! Pycro-manager actually uses multiprocessing internally so that adding acquisition events, running acquisition hooks, and running image processors don't interfere with one another. There are some ways in which multiprocessing can cause unexpected problems though. Could explain a bit more about what you're trying to do?

**Comment by josepNTU** [comment]
Hi Henry! Thanks for your kind reply :) I'm building a mapping process for my microscope. I was using snapImage() in a thread to acquire images at each point location , but snapImage() blocked Python (I'm now using MMCorePy with Python 2.7). So multiprocessing seems like the obvious next step. I'd be keen on learning about other methods. I'm quite new into the Micro-Manager community. I have seen that you are also developing the bindings for this Micro-Magellian, which seems to do mapping, but I'm not sure how it works. How would you approach mapping?

**Comment by henrypinkard** [comment]
I guess you're talking about mapping a sampling using tiling with an XY stage, correct? Micro-Magellan is pretty well set up to do this. You'll first need to download the latest nightly build of Micro-Manager 2.0 gamma. Then you'll need to calibrate the camera relative to the XY stage. Do this using the micro-manager pixel calibrator (under Devices--pixel size calibration). Then you should be able to use Explore acquisition in Magellan (https://micro-manager.org/wiki/MicroMagellan#Explore_Acquisitions)

**Comment by henrypinkard** [comment]
@josepNTU you may be interested in new features just added: https://pycro-manager.readthedocs.io/en/latest/acq_intro.html#xy-tiling to support XY tiling. I would say if you want an existing GUI to do this you should use Magellan, or if you want to build something yourself programmatically, you should use these features. 

Closing this issue since the original question is answered. Feel free to reopen another one if something else comes up
