### ISSUE TITLE
summary_metadata equivalent

### ISSUE THREAD

**Issue by kdmarchuk** [micro-manager/pycro-manager#312]
Hi Henry, 

We took some data on our SPIM using the newest version of Magellan. I'm looking to convert it to an Imaris file using the PYMARIS_Converter I wrote a couple years ago for Pygellan. To find metadata I used `magellan.summary_metadata['z-step_um']`, etc to pull a lot of information from the dataset. Is there an equivalent for pycro-manager data taken through the Magellan plugin? `read_metadata()` seems to only work on a single frame and doesn't include the experimental parameters.

Thanks!

**Comment by henrypinkard** [comment]
It should still be the same: `dataset.summary_metadata`

**Comment by kdmarchuk** [comment]
I must have messed something up testing that.

It's working, but some tags seemed to have been dropped. Where would I find the list of channel names, number of frames, and number of slices? Is there a reference of what should be in this metadata depending on acquisition parameters?

Thanks again

**Comment by henrypinkard** [comment]
Yes, the metadata names have changed somewhat since the development version. Full list is here (includes both image and summary):

https://github.com/micro-manager/AcqEngJ/blob/master/src/main/java/org/micromanager/acqj/api/AcqEngMetadata.java

There's no longer tags for total number of frames/channels/etc, since the acquisition engine lets you change this at runtime. Take a look at the API: https://pycro-manager.readthedocs.io/en/latest/apis.html#reading-acquired-data

**Comment by kdmarchuk** [comment]
Okay, so the best way of retrieving the channel names might be to find the dims of the dask array, and iterate over the number of channels using `dataset.get_metadata(channel=i, z=0, row=0, col=0)` and looking in the dict? Same for number of frames and timepoints, etc.

**Comment by henrypinkard** [comment]
No, will be much faster to call `get_index_keys()` and then process them to see which channels/frames/etc are present

**Comment by kdmarchuk** [comment]
Okay. I'll try that. Thanks for the help.
