### ISSUE TITLE
Working with array objects over the java/python bridge

### ISSUE THREAD

**Issue by ptbrown1729** [micro-manager/pycro-manager#314]
I'm not sure that this is the best forum for this question, but it did not seem appropriate for image.sc forum either. Happy to discuss in a different venue if that makes the most sense. Any help or thoughts would be appreciated!

I am trying to work with a java object which is an array over the java/python bridge with pycromanager, but I cannot figure out how to slice the array from the python side. I am trying to modify a MicroscopeModel object to remove a certain device programmatically. I am able to do this in java, but converting that code to python I cannot iterate over the devices in the MicroscopeModel object. The initial (working) part of code is:

```
import pycromanager as pm

bridge = pm.Bridge(convert_camel_case=False)
mmc = bridge.get_core()
mm = bridge.get_studio()

cfg_fname = mm.getSysConfigFile()
mm_model = bridge.construct_java_object("org.micromanager.internal.hcwizard.MicroscopeModel")
mm_model.loadFromFile(cfg_fname)
mm_model.createSetupConfigsFromHardware(mmc)
mm_model.createResolutionsFromHardware(mmc)
devs = mm_model.getDevices()
```
Now I would like to translate the following Java code to python:
```
for (d : devs){
	name = d.getName();
	if (name.contains("do")){
		mm_model.removeDevice(name);
	}
}
```

`devs` is an array of device objects. But the shadow object on the python side is not an iterator, so I cannot slice/iterate over it.  Is there a way to slice such an object using pycromanager?

It seems like the method `_translate_call` using the java function `Array.get` might be useful, but this function is not a method of `devs`. So I'm struggling to see a path forward.

**Comment by henrypinkard** [comment]
Not totally clear to me either how you would do this. Maybe you could try using [`Arrays.asList`](https://docs.oracle.com/javase/8/docs/api/) to convert to `ArrayList` then manually iterate through the devices. Though this might be weird because the Bridge doesn't natively support static methods right now, so you'd need to instantiate an `Arrays` object first. Unclear to me if this would work but worth a try maybe.

If that doesn't work, the quick and hacky way to get this workign would be to do a pull request adding a `getDevicesAsArrayList()` method to the Java side. Other solutions would probably require some substantial changes to the bridge

**Comment by ptbrown1729** [comment]
@henrypinkard thanks for looking into this. I will give the ArrayList method a shot

Right now my work around is to run this portion of my acquisition code in beanshell. Then from beanshell I call a python script which uses pycromanager to automate the rest of the experiment. Sort of convoluted, but it works.

**Comment by henrypinkard** [comment]
Sounds like a good workaround. Hopefully some of these features can be fleshed out in the future to make this type of thing easier

**Comment by ilyasdc** [comment]
Any new idea on the subject ? I tried to invoke the `Arrays` class but it doesn't work,  `construct_java_object("java.util.Arrays")`  fails:

```
Exception: No valid java constructor found with classpath java.util.Arrays
```

**Comment by henrypinkard** [comment]
Its definitely possible. I just haven't had to time to implement. There just needs to be additional support for static Java objects. I Could guide you through if you're interested in taking a stab at implementing

**Comment by ilyasdc** [comment]
> 

Hi Henry,

The problem lies on the Java side, correct ? If so I fear that my knowledge of that language is extremely limited. But I can have a look if you are willing to guide me !

**Comment by henrypinkard** [comment]
Thanks for offering, but unfortunately this lives in the deepest, darkest, most java-y parts of the code.

I'll try to take a stab at at

**Comment by henrypinkard** [comment]
I think I got it working. But wondering what you're planning to do with the `Arrays` class specifically? A lot of the methods that class has dont translate so well, because the bridge copies all array data every time one is passed as an argument or returned. So something like `Arrays.fill` is going to just create an array on the java side and fill it, but this wont affect the numpy array you passed in

**Comment by henrypinkard** [comment]
added in #365
You can now call `bridge.get_java_class("java.util.Arrays")` to get a class on which you can call static methods

**Comment by henrypinkard** [comment]
The original issue of arrays of objects needs to be added

**Comment by ilyasdc** [comment]
Hi @henrypinkard  and thank you for taking this matter at hand so promptly. I pulled the last version of MM and pycro-manager and could check that I could indeed retrieve the `Arrays` class.

My issue, somehow different, remains unsolved. Some methods return `java.lang.String[]` my idea was to use this `Arrays` class to convert them to `ArrayList` but that doesn't work. 

Those arrays are not correctly retrieved since they show a wrong type: `<pycromanager.zmq.[Ljava_lang_String; at 0x7f2ad8b453d0>` (notice the `;`)

Should I open another issue on the subject ? It's probably not at the top of your priority list, but it's not absolutely needed either.

Last thing I couldn't find a way to retrieve all elements in `ArrayList` except in a convoluted way and I made a little change to iterate over them automatically, maybe it's already possible and I wasn't aware of it, if not you can find my commit here: https://github.com/ilyasdc/pycro-manager/commit/c672ed0f70e1c4e22f6e23cc8a746429795cc392

**Comment by henrypinkard** [comment]
> Those arrays are not correctly retrieved since they show a wrong type: `<pycromanager.zmq.[Ljava_lang_String; at 0x7f2ad8b453d0>` (notice the `;`)

I don't quite get this. These generated class names always look a little weird to me. what is significant about the `;` to you?


> Last thing I couldn't find a way to retrieve all elements in `ArrayList` except in a convoluted way and I made a little change to iterate over them automatically, maybe it's already possible and I wasn't aware of it, if not you can find my commit here: [ilyasdc@c672ed0](https://github.com/ilyasdc/pycro-manager/commit/c672ed0f70e1c4e22f6e23cc8a746429795cc392)

I think you can always just call `[array_list.get(index) for index in range(array_list.size()) ]`, but your way is a lot nicer. You should PR this in, but a few things first:

- You should stick the `java_iter` somewhere in the `JavaObjectShadow` Class
- Your function needs to account for camelCase: `has_next` vs `hasNext`
- There needs to be some flag to turn this behavior on/off in case people actually want to use the `ArrayList` Object itself. Maybe `JavaObjectShadow._convert_lists`
- bump the patch version (3rd number [here](https://github.com/micro-manager/pycro-manager/blob/main/pycromanager/_version.py))

**Comment by henrypinkard** [comment]
> My issue, somehow different, remains unsolved. Some methods return `java.lang.String[]` my idea was to use this `Arrays` class to convert them to `ArrayList` but that doesn't work.

I think this might need to be some changes to specifically handle the case of `String[]`, and I'm not sure if its the same as how to handle `Object[]`. any ideas?

**Comment by ilyasdc** [comment]
> > Those arrays are not correctly retrieved since they show a wrong type: `<pycromanager.zmq.[Ljava_lang_String; at 0x7f2ad8b453d0>` (notice the `;`)
> 
> I don't quite get this. These generated class names always look a little weird to me. what is significant about the `;` to you?
> 

I think doesn't appear for other base type arrays but maybe I'm just too focused on the representation but I agre this might be unimportant.

> > Last thing I couldn't find a way to retrieve all elements in `ArrayList` except in a convoluted way and I made a little change to iterate over them automatically, maybe it's already possible and I wasn't aware of it, if not you can find my commit here: [ilyasdc@c672ed0](https://github.com/ilyasdc/pycro-manager/commit/c672ed0f70e1c4e22f6e23cc8a746429795cc392)
> 
> I think you can always just call `[array_list.get(index) for index in range(array_list.size()) ]`, but your way is a lot nicer. You should PR this in, but a few things first:
> 
>     * You should stick the `java_iter` somewhere in the `JavaObjectShadow` Class
> 
>     * Your function needs to account for camelCase: `has_next` vs `hasNext`
> 
>     * There needs to be some flag to turn this behavior on/off in case people actually want to use the `ArrayList` Object itself. Maybe `JavaObjectShadow._convert_lists`
> 
>     * bump the patch version (3rd number [here](https://github.com/micro-manager/pycro-manager/blob/main/pycromanager/_version.py))

Sure, happy to contribute, I'll do that soon.

> I think this might need to be some changes to specifically handle the case of `String[]`, and I'm not sure if its the same as how to handle `Object[]`. any ideas?

No, sorry, but how are the base type (especially array) handled ? And is it possible to directly retrives the bytes contained in the object (which one can easily decode I guess in the case of a string array)

**Comment by henrypinkard** [comment]
> > I think this might need to be some changes to specifically handle the case of `String[]`, and I'm not sure if its the same as how to handle `Object[]`. any ideas?
> 
> No, sorry, but how are the base type (especially array) handled ? And is it possible to directly retrives the bytes contained in the object (which one can easily decode I guess in the case of a string array)

The primitive arrays (`byte[]`, `int[]`, etc) are specifically converted to bytes and then decoded into numpy arrays. But I don't think that would work with strings in the exact same way since there can be variable numbers chacters for each one. I might just need to write something explicit to handle it that converts to a python list of strings

**Comment by ilyasdc** [comment]
> 

Hi, I updated my code, I of course forgot to increment the patch version but tell me if what's left is fine for you (https://github.com/ilyasdc/pycro-manager/commits/iterable). Sorry but I've messed up the commits order, if that's a problem I can work on it.

**Comment by ilyasdc** [comment]
Hi, 
I have a hard time with git but after 4 or 5 forced push I'm giving up and will let this ugly merge commit. Merging from the PR interface is possible. I still need to increment the version number, or you can do it I guess. Let me know.

**Comment by henrypinkard** [comment]
Yeah git can definitely be a pain at first. I'm happy to increment the version. Let me know if I can otherwise help

**Comment by ilyasdc** [comment]
> Yeah git can definitely be a pain at first. I'm happy to increment the version. Let me know if I can otherwise help

I just submitted the PR. Is there any test that needs to be performed ? I quickly ched with and without camel case and with and without the option enabled but maybe I should do more extensive testings

**Comment by henrypinkard** [comment]
Awesome. Unfortunately there's no automatic testing for this layer at the moment. I'll give it a run through to make sure everything is still working

**Comment by henrypinkard** [comment]
Seems good. Thanks for the contribution!
