### ISSUE TITLE
Separate Image Files

### ISSUE THREAD

**Issue by jowch** [micro-manager/pycro-manager#321]
Hello! I have looked around and I wasn't able to find any reference to saving images as separate image files like how micro-manager itself allows us to do. Does pycro-manager support this? If so, how can I do this?

**Comment by henrypinkard** [comment]
Pycro-manager only saves in [NDTiff](https://github.com/micro-manager/NDTiffStorage) format. If you want to save 1 image per a file (using pycromanager Acquisitions), you can implement an [image processor](https://pycro-manager.readthedocs.io/en/latest/img_processors.html) that rather than processing and passing on images, diverts them to your own custom saving

**Comment by jowch** [comment]
Thanks! I figured I could do something like that but wanted to check if I missed something.
