### ISSUE TITLE
How to make system pause until image processing is complete

### ISSUE THREAD

**Issue by michaelpmay** [micro-manager/pycro-manager#336]
Hello, 

I am trying to do an acquisition of a set of images, and using each image I zap the nucleus with a 405 laser.

I would like to write an image processing hook that uses the image and finds the centroid of the nucleus and then zaps the corresponding position, but the acquisition loop and the image processing loop are not synchronized and I am not zapping the correct positions.

Is there any way to do image processing, but make the acquisition halt until it completes?

I have tried writing a post_camera_hook function which does the image processing in order to pause the system, but I need to use core.snap to get an image which will bleach the sample faster.

Thanks!

**Comment by henrypinkard** [comment]
Yes, you to add acquisition events from within the processor, rather than usign `acq.acquire`. 

Though you do need to do `acq.acquire` with at least one event to kick off the processor

Example, here: 

https://pycro-manager.readthedocs.io/en/latest/img_processors.html#adapting-acquisition-from-image-processors
