### ISSUE TITLE
how to close after start headless?

### ISSUE THREAD

**Issue by ianhi** [micro-manager/pycro-manager#390]
how do you programmatically close everything after start headless? i.e. close the bridge and shutdown the java subprocess

**Comment by ianhi** [comment]
relevant for: https://github.com/ianhi/pycro-plus-bridge/pull/1

**Comment by henrypinkard** [comment]
The bridge will close itself automatically when its desctructor runs after any Java objects are no longer in use.

The java subprocess that contains the core is just meant to automatically shut down when the python process that calls it ends, since you usually don't need to be creating and destroying cores in a single python script. But wouldn't be too hard to add a method to kill the subprocess if its needed

**Comment by ianhi** [comment]
This will be closed by https://github.com/micro-manager/pycro-manager/pull/392
which should enable

```python
from pycromanager.acq_utils import cleanup
cleanup()
```
to close any open subprocesses
