### ISSUE TITLE
image_saved_fn hook with four arguments

### ISSUE THREAD

**Issue by ieivanov** [micro-manager/pycro-manager#427]
It would be useful to extend the `image_saved_fn` of the `Acquisition` class to take four arguments: image, metadata, bridge, and event_queue, similarly how the `image_process_fn` works. In this way we can modify the hardware and create new acquisition events based on feedback from the save dataset and overcome python-java data throughput limitations (https://pycro-manager.readthedocs.io/en/latest/img_processors.html#performance)

**Comment by henrypinkard** [comment]
Good idea, and should be pretty easy to do. Though I would say makes more sense to change it to 3 parameters, and not include the bridge, since the bridge is supposed to be hidden behind the scenes in the current version--I've been to change it to a three argument signature. 

I may not have a chance to do this myself for a few weeks though. Do you want to take a shot at it? it would be purely in python, and you'd essentially just have to copy what the `image_process_fn` does in checking the number of arguments

**Comment by ieivanov** [comment]
Yup, I can take care of that. Thanks for the pointers, I wasn't sure if there is work to be done on the Java side also.

**Comment by henrypinkard** [comment]
@ieivanov 
Was making some related changes and just added this (https://github.com/micro-manager/pycro-manager/pull/445)

**Comment by henrypinkard** [comment]
But it on has 3 arguments because explicitly accessing the bridge is no longer needed

**Comment by ieivanov** [comment]
Thanks @henrypinkard! This will be useful to @rachel-banks
