### ISSUE TITLE
Unexpected behavior multi_d_acquisition_events

### ISSUE THREAD

**Issue by ssalteko** [micro-manager/pycro-manager#444]
Hello, 

I am using multi_d_acquisition_events to generate z-stacks and I am getting unexpected results. 

It seems that when the resulting value of "z_start - z_end" is positive, that no events are generated. I would expect the sign to not be an issue. Here is some code to hopefully make the issue clear. 
from pycromanager import  multi_d_acquisition_events

z_start_p1 = 5
z_start_p2 = 1

z_end_p1 = 4
z_end_p2 = 1

z_start_n1 = -5
z_start_n2 = -1

z_end_n1 = -4
z_end_n2 = -1

z_step_1 = 1
z_step_2 = 4

xyz = [[0,0,0],
       [939.189,0,0]]

events1 = multi_d_acquisition_events(xyz_positions = xyz,
                                            z_start = z_start_n1,
                                            z_end = z_end_n1,
                                            z_step = z_step_1
                                            )

print(f'{events1 =}   {z_start_n1 - z_end_n1}')

events2 = multi_d_acquisition_events(xyz_positions = xyz,
                                            z_start = z_start_p1,
                                            z_end = z_end_p1,
                                            z_step = z_step_1
                                            )

print(f'{events2 =}  {z_start_p1 - z_end_p1}')

events3 = multi_d_acquisition_events(xyz_positions = xyz,
                                            z_start = z_end_n1,
                                            z_end = z_start_n1,
                                            z_step = z_step_1
                                            )

print(f'{events3 =}    {z_end_n1 - z_start_n1}')

events4 = multi_d_acquisition_events(xyz_positions = xyz,
                                            z_start = z_end_p1,
                                            z_end = z_start_p1,
                                            z_step = z_step_1
)

print(f'{events4 =}    {z_end_p1 - z_start_p1}')

**Comment by ssalteko** [comment]
Thanks for getting back to me so quick. 

That line is supposed to show a list of events as output by the multi_d_acquisition_events, followed by the value of z_end subtracted from z_start. 

For what ever reason when that value is positive the events list comes out empty. I was recently working on a script for someone and I noticed it. I kept getting an empty events list when I would use z-stacks with the multi_d_acquisition_events. When I reversed the order of the numbers everything worked. I carried on with life and figured it was just my weird computer. Then the end user noticed it, I told them to reverse their values of z_start and z_end and it started working. I then thought it is probably not just my computer/nightly builds and might be a bug and worth my very first github issue ever! (balloons and confetti)

**Comment by henrypinkard** [comment]
That makes sense. Any interest in making your first pull request/open source contribution? I'm happy to guide you through the process

**Comment by ssalteko** [comment]
I am interested. How do I start?

**Comment by henrypinkard** [comment]
Great!

The first step is setting up the dev environment, for which you can follow the instructions here: https://github.com/micro-manager/pycro-manager/blob/main/Contributing.md

In terms of changes, you're going to want to make changes the function that generates multi-d acquisition events:
https://github.com/micro-manager/pycro-manager/blob/fd7fd8281088e9aec9904bf23ba83fe4759df899/pycromanager/acq_util.py#L112

Once you've done that, you can write add one or more tests to this file
https://github.com/micro-manager/pycro-manager/blob/main/pycromanager/test/test_MDA_events.py, which serves to check that events generated are what you would expect for calls to the function (so in your case, you expect it to generate events rather than generating nothing). You can run the test script locally, and once it gets added to pycro-manager, it will run in the future so that it ensures no one breaks this behavior (and it will ensure your changes don't break any of the existing expected behaviors).

It may be helpful to look through [this example](https://pycro-manager.readthedocs.io/en/latest/application_notebooks/multi-d-acq-tutorial.html) notebook which has a bunch of uses of the MDA function.

Let me know if you have any questions along the way

**Comment by ssalteko** [comment]
Excellent. I will try to get this going in the next few days. I am out of office next week. Thanks for all of your help.

**Comment by ssalteko** [comment]
I picking away at this finally. It seems the issue involves z_rel = np.arange. The arange function seems to be picky about the bigger number coming second.  I think I know what to do, but I will sleep on it.

**Comment by ieivanov** [comment]
When using a descending z-stack (i.e. `z_start` > `z_end`) `z_step` needs to be negative, which makes sense. For example:

```python
print(multi_d_acquisition_events(z_start=0, z_end=3, z_step=1))
[{'axes': {'z': 0}, 'z': 0}, {'axes': {'z': 1}, 'z': 1}, {'axes': {'z': 2}, 'z': 2}, {'axes': {'z': 3}, 'z': 3}]

print(multi_d_acquisition_events(z_start=3, z_end=0, z_step=-1))
[{'axes': {'z': 0}, 'z': 3}, {'axes': {'z': 1}, 'z': 2}, {'axes': {'z': 2}, 'z': 1}, {'axes': {'z': 3}, 'z': 0}]
```

**Comment by ssalteko** [comment]
@ieivanov You are correct. I just got the same thing to work and it seemed easy enough to implement.

**Comment by ieivanov** [comment]
Glad it worked!

I'll close this issue for now. Let us know if you run into any other problems.
