### ISSUE TITLE
pycromanager acquisition does not work in 0.20.0

### ISSUE THREAD

**Issue by ieivanov** [micro-manager/pycro-manager#449]
Pycromanager acquisition with the demo config running on nightly build 2022_11_07 and a call to 

```python
from pycromanager import Core, Acquisition, multi_d_acquisition_events

events = multi_d_acquisition_events(num_time_points = 10)
with Acquisition(directory=r'Q:\Ivan\debug', name='PM_test') as acq:
    acq.acquire(events)
```

throws the following error:

```
Exception: java.lang.NullPointerException
org.micromanager.ndviewer.main.NDViewer.<init>(NDViewer.java:102)
org.micromanager.ndviewer.main.NDViewer.<init>(NDViewer.java:92)
org.micromanager.remote.RemoteViewerStorageAdapter.createDisplay(RemoteViewerStorageAdapter.java:122)
org.micromanager.remote.RemoteViewerStorageAdapter.initialize(RemoteViewerStorageAdapter.java:104)
org.micromanager.acqj.main.Acquisition.initialize(Acquisition.java:272)
org.micromanager.acqj.main.Acquisition.<init>(Acquisition.java:89)
org.micromanager.acqj.main.Acquisition.<init>(Acquisition.java:77)
org.micromanager.remote.RemoteAcquisition.<init>(RemoteAcquisition.java:24)
org.micromanager.remote.RemoteAcquisitionFactory.createAcquisition(RemoteAcquisitionFactory.java:53)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
org.micromanager.internal.zmq.ZMQServer.runMethod(ZMQServer.java:388)
org.micromanager.internal.zmq.ZMQServer.parseAndExecuteCommand(ZMQServer.java:466)
org.micromanager.internal.zmq.ZMQServer.lambda$initialize$2(ZMQServer.java:117)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)
```

**Comment by henrypinkard** [comment]
There was a bug introduced to NDViewer, which is now fixed. However, there's something weird going on with my IDE so I haven't been able to successfully test (a reference is null even though this is impossible given the code).

It may be fixed by dropping in the new [NDViewer](https://s01.oss.sonatype.org/service/local/repositories/releases/content/org/micro-manager/ndviewer/NDViewer/0.6.6/NDViewer-0.6.6.jar)? Still working through the other stuff

**Comment by ieivanov** [comment]
Tried the new viewer - the acquisition doesn't error out in the same way, but instead hangs without acquiring data. Something is still not quite right.

**Comment by ieivanov** [comment]
Tried the new viewer - the acquisition doesn't error out in the same way, but instead it hangs without acquiring any data. Something is still not quite right.

**Comment by henrypinkard** [comment]
Ok I found the actual culprit. Should be fixed in [new version](https://s01.oss.sonatype.org/service/local/repositories/releases/content/org/micro-manager/ndviewer/NDViewer/0.6.7/NDViewer-0.6.7.jar)

Will look at the acq bug tomorrow. There were some big changes related to getting the micro-manager GUI MDA to run on AcqEngJ so I assume its related to that
