### ISSUE TITLE
pycromanager 0.19.2 fails with sequenced acquisitions

### ISSUE THREAD

**Issue by ieivanov** [micro-manager/pycro-manager#450]
Using the `MMConfig_demo.cfg` config pycromanager 0.19.2 can acquire a dataset using 

```python
from pycromanager import Core, Acquisition, multi_d_acquisition_events

mmc = Core()
mmc.set_property('Z', 'UseSequences', 'No')

events = multi_d_acquisition_events(z_start = 0, z_end = 10, z_step = 1)

with Acquisition(directory=r'Q:\Ivan\debug', name='PM_test2', debug=False) as acq:
    acq.acquire(events, keep_shutter_open=True)
```

but fails if Z sequencing is turned on (`mmc.set_property('Z', 'UseSequences', 'Yes')`) with error

```
Exception: java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.micromanager.acqj.internal.HardwareControlException
org.micromanager.acqj.internal.Engine.lambda$submitEventIterator$4(Engine.java:176)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)
```

A similar error is thrown if using channel sequencing (rather than z sequencing). Subsequent non-sequenced acquisitions also fail with error saying `org.zeromq.ZMQException: Errno 48 : Address already in use`.

The same issue likely persists in the current pycromanager version.

**Comment by henrypinkard** [comment]
I can reproduce this, but I was just looking through our previous conversation in https://github.com/micro-manager/pycro-manager/issues/88, and based on the conversation there I thought the `keep_shutter_open` flag is for non-hardware sequenced acquisitions? Is that correct or are you actually using it for hardware-sequenced acquisitions?

I'm not sure where this broke, though it should be pretty easy to fix. However, looking back on this, and thinking about further integration with MM MDAs and adding more features, I'm thinking it might actually make more sense to remove `keep_shutter_open` from the API. The reason is I think this could be much more cleanly implemented after I've added the ability to customize the ability to specify what hardware changes occur in an acquisition (https://github.com/micro-manager/micro-manager/issues/1524), and I think that will likely require deprecating this feature anyway.

In the meantime, I think this behavior could be controlled from acquisition hooks. What do you think about this? Do you think it would work as a temporary solution?

```python

num_z_steps = 10

def hook_fn(event):
   core = Core() 
   if event['axes']['z'] == 0:
       core.set_auto_shutter(False)
       core.set_shutter_open(True)
   elif event['axes']['z'] == num_z_steps - 1:
       core.set_auto_shutter(True)
       core.set_shutter_open(False)

    return event

# pass in the function as a post_hardware_hook
with Acquisition(directory='/path/to/saving/dir', name='acquisition_name',
                pre_hardware_hook_fn=hook_fn) as acq:
    ### acquire some stuff ###
```

**Comment by ieivanov** [comment]
Sorry, I think the `acq.acquire(events, keep_shutter_open=True)` line in this example is leftover from a larger test I did. I believe PM handles the shutter correctly even if this argument is left out.

I'd be in support of removing `keep_shutter_open` from the API and handling shutter behavior in a cleaner way. I'm still a bit unsure of when to use that vs the `keep_shutter_open` key in the events list.

**Comment by henrypinkard** [comment]
Okay cool. I'll go ahead and do that while fixing this

**Comment by ieivanov** [comment]
Confirmed this is fixed
