### ISSUE TITLE
Access to static Java classes

### ISSUE THREAD

**Issue by henrypinkard** [micro-manager/pycro-manager#52]
There's currently no way to access static fields of a class without creating an instance of that class. The solution is most likely to create a parallel function to `construct_java_object`, `construct_java_class`, which just gets you a Python version of the class plus static methods + fields. This will require changes in `core.py` as well as in `ZMQServer.java`

**Comment by nicost** [comment]
Commenting on this to make @marktsuchida aware of the problem.  His new API design often makes use of static "Builder" classes to generate objects (such as the Coordinates builder), rather than give direct access to a Builder, Constructor, or have a method to generate the needed object.  Currently, there are deprecates methods that still make it possible to get things to work, but the planned API design combined with the current inability of Pycro-Manager to access static fields and methods is not a good thing.  I can not oversee how difficult it is to implement the changes you describe, but I would know how to avoid static fields an methods in the MM Java API.

**Comment by henrypinkard** [comment]
It's certainly doable, though would take a bit of testing. However, I think that the static "Builder" paradigm is not something one encounters much in Python, and as such I wouldn't expect this to be very intuitive to someone with only Python experience. So in the interest of making this API more accessible it might be worth considering a regular constructor paradigm.

**Comment by marktsuchida** [comment]
@nicost I'm not sure I understand what you mean by 'makes use of static "Builder" classes ... rather than give direct access to a Builder ...'. Are you referring to the fact that `DefaultCoords` and `DefaultCoords.Builder` are not in the public API and the fact that `Coordinates.builder()` is a static method? What would be the alternative?

I think there might be other possibility for the specific case of `Coords`, but surely you are not proposing that we eliminate all static (fields and) methods from the MMStudio Java API, are you?

Am I understanding correctly that this issue is about static fields and methods, rather than "static classes"?

Could you fill me in on what exactly is the technical difficulty in accessing static fields and methods? To me (without being aware of details) the approach @henrypinkard suggested above (of providing a proxy for the Java class object) makes perfect sense, especially because normal classes are also objects in Python -- it should feel natural (or as natural as cross-language access can be). It might also be useful to take a look at how other Python-to-Java interfaces (e.g. JPype) provide access to static fields and methods.

**Comment by nicost** [comment]
The fact that Coordinates.builder() is a static method.  Alternative is to have a non-static method that is part of the DataManager class, such as mm.data().coordsBuilder() (or similar).

Any solution is fine with me, and it would be simplest to have non-static methods available on the Java side to provide these Builders.  Also fine to patch pycro-manager to give access to static Java classes and methods, but that is certainly not something I would know how to do.  Given the cool things that pycromanager accomplishes, I do believe it should be a priority to ensure that the full MM api is available through this interface.

**Comment by marktsuchida** [comment]
Hmm, I see. I guess it would be relatively harmless to re-add a `coordsBuilder()` to `DataManager`, as long as we keep the static `Coordinates.builder()`, though it's not ideal to have two ways to do the same simple thing.

Also, we could perhaps complement most, if not all, of the "collection of static methods" type of classes with instance versions. I haven't thought this through, but if we do this under uniform rules it should be cleaner than adding to the already crowded "managers". (Although I would prefer to have a good Java-oriented reason to do this, because it is anti-DRY.)

But it's hard enough to design a good API without arbitrary restrictions. I would be much more willing to help fix pycro-manager than try to contort the MMStudio API to fit these requirements in all cases.

Is there any particular technical difficulty in accessing static methods, or is it just work that needs to be done?

**Comment by henrypinkard** [comment]
Work that needs to done but doesn't seem likely to be done any time soon

**Comment by Thrameos** [comment]
Not sure if this is useful to you (popped up on JPype search),   JPype uses Python class wrappers which are represent the class, its constructors, array contructors, and all static member fields.   The constructors are actually in a meta class one level up so that they don't appear in the instance type.  The instances of those classes hold the instance fields and methods and because they are class instances they inherit the static methods and fields.   The class actually has the instance methods and non static fields but those use the bound method pattern as descriptors in Python.   So if you give them a class instance they could be called statically from the class wrapper.  Last because JPype is to represent Java structures there is a property called ``class_`` which is an instance of java.lang.Class holding all the reflection.   All of these are generated dynamically via reflection and Python meta class programming.  

Most of this is given in great deal in the developer guide if you are interested in creating a similar wrapper type structure for your IPC based model (guessing based on the project description).

This does allow for builder type APIs to be used in Python.   The readability of this in Python is pretty high but as noted here may not be the most familiar to Python programmers.,

For example some code using a proprietary gamma ray radiation detection library that I develop 
```
from gov.llnl.rtk.test import SampleGenerator
...
sgb = SampleGenerator.newBuilder(gsm)
b0 = sgb.add(bkg[0]).setTime(300).scaleToRate(1000).create()
```

Hope it helps.
