### ISSUE TITLE
Drag-and-drop of data into MM does not work

### ISSUE THREAD

**Issue by ieivanov** [micro-manager/pycro-manager#54]
Loading data into MM by drag-and-drop into the gui window does not work. A progress bar is created, but data are not loaded.

**Comment by henrypinkard** [comment]
This would not be expected to work. Pycro-manager uses different libraries for data storage (https://github.com/micro-manager/NDTiffStorage) and image viewing (https://github.com/micro-manager/NDViewer) than the ones in micro-manager, in order to support additional features like arbitrary image dimensions, multi-resolution pyramids, and flexible modification/injection/deletion of image data on-the-fly. I do think it would be a very nice feature to support though, if you're interested in taking a stab at adding it (would be on the Java side).

**Comment by ieivanov** [comment]
Ah, I see. I think coding that is beyond my abilities, though... I did see somewhere that you support viewing with `napari`, I'll give that a try.
