### ISSUE TITLE
Wait for acquisition events to finish

### ISSUE THREAD

**Issue by ieivanov** [micro-manager/pycro-manager#567]
I have an application where I would like to send a batch of acquisition events, wait for them to complete, modify the microscope, and then send another batch of acquisition events. It would be convenient for me to do this outside of the acquisition hook functions. Something like this:

```python
acq = Acquisition()

for i in range(10):
    # modify microscope

    acq.acquire({'axes': {'time': i}})

    # wait for acquisition events to finish
    while not acq_events_finished()
        time.sleep(1)

acq.mark_finished()
acq.await_completion()
```

Is that currently possible? What should `acq_events_finished()` be? To me a bit more specific, between calls to `acquire()` I would like to move between positions, run autofocus, and dispatch events to two parallel acquisitions only if autofocus succeeds. My other alternative is to do that through the pre- and post hardware hook funcions.

**Comment by henrypinkard** [comment]
The hook would be the way to do this through the current API, but I agree it would be a lot simpler to do have something that runs without so that you can do this type of thing without worrying about thread synchronization--essentially making the main python thread synchronous with the hardware control thread. This is fine if you're not doing anything on that thread.

The essential idea of this is I think to have `acq.acquire` return a `Future`, on which you could call `.get()`, which will then block until that batch of events is finished. Though finished can mean different things--event executing, camera triggered, image acquired, or image saved. The logic for synchronizing on any of these is already present in AcqEngJ, it would just be a matter of exposing that through python. If you just want to do sync on image saving you could implement this with the existing API. Exposing any of those would require some reworking under the hood to allow python to wait on those Java `Future`s. A bit of work, though doable (and would definitely be a nice feature to have)

**Comment by henrypinkard** [comment]
I think the way to do this is to add an additional socket, which the python `Acquisition` class listens for events published by the AcquisitionEngine. That way, you can get all the relvant stuff, events executing, camera triggered, etc. And it would be generic so more stuff could be added in the future. Much better to do it this way than to be monitoring waiting on `Future`s from specific java objects. I'm happy to look into adding this.

**Comment by ieivanov** [comment]
That would help, thanks! My current hacky way to do this is to use the `image_saved_fn` hook and check whether the image axis corresponds to the last axis of the events I sent out. I found that this really slows down the acquisition over time - at first I can go between positions in 15 seconds, and a few thousand images later, this time does up to two minutes. I'll confirm that this is due to the `image_saved_fn` and will create a proper issue. My next move was to use the `pre_hardware_hook_fn` instead, which would not be as clean, but can still work. The more proper implementation you suggest would likely be much more robust.

**Comment by henrypinkard** [comment]
Moving towards implementation, discussion on: https://github.com/micro-manager/pycro-manager/issues/654
