### ISSUE TITLE
keep track of position label

### ISSUE THREAD

**Issue by ieivanov** [micro-manager/pycro-manager#575]
One useful thing that is currently lost with a pycromanager acquisition is the position label. In my workflow, I use the [HSC Site Generator](https://micro-manager.org/HCS_Site_Generator) to generate a position list with multiple FOVs per well, which I then import in python and pass the XYZ coordinates to pycromanager. However, I don't have a way to pass the position label. It's important to know which position index comes from which well, so currently I write a csv file to keep track of this information.

Could the `position` axis in the events dictionary become a string axis, just like `channel`, such that the position label can be used as the axis index? Could it be either an integer or string (is that how the `channel` axis works currently)? Is there a way to quickly iterate through the positions even if we don't know the labels ahead of time? Can we still keep track of the order in which the positions are acquires? I would think all of this should be possible on the python side.

**Comment by henrypinkard** [comment]
> Could the `position` axis in the events dictionary become a string axis, just like `channel`, such that the position label can be used as the axis index? Could it be either an integer or string (is that how the `channel` axis works currently)?

Yes, it should be the case that any axis can take integer or string values, just not both within a single axis. So you should be able to switch and index them by label.

> Is there a way to quickly iterate through the positions even if we don't know the labels ahead of time?


```python
for value in dataset.axes['position']:
```


> Can we still keep track of the order in which the positions are acquires?

Yes, this should possible. `dataset.axes` is a dict that has a list for the values of each axis. For example:

```python
{'row': [-2, -1, 0, 1],
 'column': [-2, -1, 0, 1, 2],
 'channel': ['Brightfield', 'FITC', 'TRITC'],
 'z': [0]}
```

So there is an order in there. Right now these are sorted alphabetically/numerically. The `dataset.as_array` function needs the numerical sorting. For example, if a z stack wasn't acquired in order, you don't want it to be returned in non-spatial order. However, I think the sorting could be moved into `as_array`, and `dataset.axes` kept in acquisition order.

You'd also need to I think change this from a dict to an [OrderedDict](https://docs.python.org/3/library/collections.html#collections.OrderedDict) for datasets read from disk:


https://github.com/henrypinkard/NDTiffStorage/blob/0eee9476342d61c4308161c35c3a9951a91f4a63/python/ndtiff/nd_tiff_current.py#L599
 
(it might work as is because in my experience regular dicts behave as ordered, but the language doesnt guarantee it as far as i understand)


and similarly here for datasets that are currently being acquired:

https://github.com/henrypinkard/NDTiffStorage/blob/0eee9476342d61c4308161c35c3a9951a91f4a63/python/ndtiff/nd_tiff_current.py#L432

Then remove the sorting that occurs at 

https://github.com/henrypinkard/NDTiffStorage/blob/0eee9476342d61c4308161c35c3a9951a91f4a63/python/ndtiff/nd_tiff_current.py#L432

and 

https://github.com/henrypinkard/NDTiffStorage/blob/0eee9476342d61c4308161c35c3a9951a91f4a63/python/ndtiff/nd_tiff_current.py#L234

**Comment by ieivanov** [comment]
Thanks! Do I understand correctly that nothing needs to change on the Java side? This shouldn't be hard for me to do then

**Comment by henrypinkard** [comment]
Yeah thats right. Cool
