### ISSUE TITLE
Different recording format from NDTIFF

### ISSUE THREAD

**Issue by jacopoabramo** [micro-manager/pycro-manager#671]
Greetings,

I'm currently experimenting with pycro-manager in headless mode. Would it be possible to specify a different file format to store data on disk? I would be interested in using for example a Zarr file writer (using for example [this](https://github.com/constantinpape/z5/tree/master) implementation to hopefully keep a good writing speed).

**Comment by henrypinkard** [comment]
Yes, it is possible to do this with [image processors](https://pycro-manager.readthedocs.io/en/latest/img_processors.html)

However, if speed is the main purpose, this approach will almost certainly be slower than using the default NDTiff writer, which is quite fast. It can easily maintain 1 GB/s on a single nvme drive indefinitely, and can go even faster on RAID setups.

Regardless of the speed of the zarr writer, streaming the image data between the processes is no faster than 100-200 MB/s. Though I hope to improve headless mode and increase this in the future, which would make adding support for something like this a nice option

**Comment by jacopoabramo** [comment]
Hi @henrypinkard , thanks for replying. Is the speed limitation due to the Zarr format itself or you're doing something in particular with the NDTiff format?

**Comment by henrypinkard** [comment]
Right now, its primarily the speed of the inter-process data transfer.

Once I've had a chance to address that, there's still the question of whether zarr format can be as fast. The problem is that there is overhead to opening new files on disk, and so to go fast you need to minimize doing that and instead write chunks of data in sequence to the same, large file. Zarr was originally designed to produce many smaller files, and not store multiple chunks in the same file. As far as I know, that feature has yet to been added.

Also see this discussion: https://github.com/micro-manager/micro-manager/issues/1243#issuecomment-1594034691

**Comment by henrypinkard** [comment]
> you're doing something in particular with the NDTiff format?

There's also many optimizations in the NDTiff writer to maximize its speed

**Comment by henrypinkard** [comment]
Update: I've added a new python backend, so you can now `start_headless(python_backend=True)` and it will run the python acquisition engine instead of the java one. This means you won't be limited by the speed of the interprocess transfer, and if your goal is to save in a different format, you should be able to do that at high speed using an `image_process_fn` to divert images to your own endpoint. It's pretty new and untested at this point, so if you give it a try, let me know how it goes.
