### ISSUE TITLE
`mmc.get_image()` should return the correct shape 

### ISSUE THREAD

**Issue by oeway** [micro-manager/pycro-manager#89]
Currently, calling `mmc.get_image()` via pycromanager will return a 1-d array, I think would be nice to return the correct shape (although we can do `mmc.get_tagged_image` but that may be slightly slower than `mmc.get_image`). This would be also nice since using `pymmcore` directly in Python would return the correct shape.

**Comment by henrypinkard** [comment]
I agree that this would be a nice feature to have, but unfortunately I think it would be very difficult to add. All of the calls to `mmc` are going through Java to the c++ core. `MMCoreJ` is the the Java wrapper around the core object (i.e. the Java analog to `pymmcore`), and its API determines what type ultimately ends up in pycromanager. In Java, pixels are represented as 1-D arrays--either `byte[]` or `short[]` depending on the byte depth. I'm not sure why the choice to use 1-D arrays was made rather than 2-D arrays (maybe @nicost can comment on this), but suffice to say changing this call would break a lot of existing code in the Java layer

**Comment by henrypinkard** [comment]
Closing since this would need to change in Micro-manger SWIG layer, not pycro-manager
